# Generated by Django 4.1.2 on 2023-03-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "fees_receipt_no",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("dep", models.CharField(max_length=20)),
                ("year", models.IntegerField(default=0)),
                ("roll_no", models.CharField(max_length=20)),
                ("tution_fees", models.IntegerField(default=0)),
                ("admission_fees", models.IntegerField(default=0)),
                ("id_fees", models.IntegerField(default=0)),
                ("management_fees", models.IntegerField(default=0)),
                ("lib_fees", models.IntegerField(default=0)),
                ("assn_fees", models.IntegerField(default=0)),
                ("rr_fees", models.IntegerField(default=0)),
                ("swf_fees", models.IntegerField(default=0)),
                ("twf_fees", models.IntegerField(default=0)),
                ("lab_fees", models.IntegerField(default=0)),
                ("sp_fees", models.IntegerField(default=0)),
                ("nss_fees", models.IntegerField(default=0)),
                ("dev_fees", models.IntegerField(default=0)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "roll_no",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("roll_no2", models.CharField(max_length=15, null=True, unique=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "dep",
                    models.CharField(
                        choices=[
                            ("Automobile", "Automobile"),
                            ("CS", "CS"),
                            ("E and C", "E and C"),
                            ("E and E", "E and E"),
                            ("Civil", "Civil"),
                            ("Mech", "Mech"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fees_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
                ),
                ("total_fees", models.IntegerField(default=0)),
                ("collection", models.IntegerField(default=0)),
                ("balance", models.IntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
