# Generated by Django 4.1.2 on 2023-03-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="roll_no2",
        ),
    ]
