# Generated by Django 4.1.2 on 2023-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_student_roll_no2"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roll_no2",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
