# Generated by Django 4.1.2 on 2023-03-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_roll_no2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fees_details",
            name="student",
        ),
        migrations.DeleteModel(
            name="History",
        ),
        migrations.DeleteModel(
            name="Fees_Details",
        ),
    ]
