# Generated by Django 4.1.2 on 2023-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_fees_details_student_delete_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="category",
            field=models.CharField(
                choices=[("SC/ST", "SC/ST"), ("SNQ", "SNQ"), ("Others", "Others")],
                default="Others",
                max_length=20,
            ),
        ),
    ]
