# Generated by Django 4.1.2 on 2023-03-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academic_Year",
            fields=[
                (
                    "academic_year",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
