# Generated by Django 4.1.2 on 2023-03-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_academic_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fees_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
                ),
                ("total_fees", models.IntegerField(default=0)),
                ("collection", models.IntegerField(default=0)),
                ("balance", models.IntegerField(default=0)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.academic_year",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
