# Generated by Django 4.1.2 on 2023-03-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_fees_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "fees_receipt_no",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField(default=0)),
                ("total_fees", models.IntegerField(default=0)),
                ("tution_fees", models.IntegerField(default=0)),
                ("admission_fees", models.IntegerField(default=0)),
                ("id_fees", models.IntegerField(default=0)),
                ("management_fees", models.IntegerField(default=0)),
                ("lib_fees", models.IntegerField(default=0)),
                ("assn_fees", models.IntegerField(default=0)),
                ("rr_fees", models.IntegerField(default=0)),
                ("swf_fees", models.IntegerField(default=0)),
                ("twf_fees", models.IntegerField(default=0)),
                ("lab_fees", models.IntegerField(default=0)),
                ("sp_fees", models.IntegerField(default=0)),
                ("nss_fees", models.IntegerField(default=0)),
                ("dev_fees", models.IntegerField(default=0)),
                ("appn_fees", models.IntegerField(default=0)),
                ("date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
