# Generated by Django 4.1.2 on 2023-03-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_history"),
    ]

    operations = [
        migrations.DeleteModel(
            name="History",
        ),
    ]
