# Generated by Django 4.2 on 2023-05-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_roll_no2_student_reg_no2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="reg_no",
            new_name="roll_no",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="reg_no2",
            new_name="roll_no2",
        ),
    ]
