# Generated by Django 4.1.2 on 2023-06-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_rename_reg_no_student_roll_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="appn_fees",
        ),
    ]
