# Generated by Django 4.1.2 on 2023-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_application_fees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
