# Generated by Django 4.2.3 on 2023-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_number',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='abcde', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(default='12345', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone_number',
            field=models.CharField(default='12345', max_length=20),
        ),
    ]
