# Generated by Django 4.2.3 on 2023-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(default=2023),
        ),
    ]
