# Generated by Django 4.2.4 on 2023-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_student_cancel_admission_student_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dep',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('CS', 'CS'), ('E and C', 'E and C'), ('E and E', 'E and E'), ('Civil', 'Civil'), ('Mech', 'Mech'), ('Dummy', 'Dummy')], max_length=20),
        ),
    ]
